import { APIRequestContext, request } from "@playwright/test";
import { MOSAIC_GRAPHQL_URL, MOSAIC_TOKEN } from "./env";

// Direct Mosaic GraphQL access, used to VERIFY the server-side effect of a UI
// journey (e.g. that a saved view actually persisted, that a workflow batch
// really committed a linked set). Verifying at the seam — not just in the DOM —
// is what makes a golden-path scenario a real composition check.
//
// Queries here use Mosaic's autogenerated transport as it actually boots
// (list field `<plural>(limit, offset)`; root `entityHistory`). Where the exact
// generated name is deployment-dependent, callers pass it in.

export async function gqlContext(): Promise<APIRequestContext> {
  const headers: Record<string, string> = { "content-type": "application/json" };
  if (MOSAIC_TOKEN) headers["authorization"] = `Bearer ${MOSAIC_TOKEN}`;
  return request.newContext({ extraHTTPHeaders: headers });
}

export async function gql<T = any>(
  ctx: APIRequestContext,
  query: string,
  variables: Record<string, unknown> = {},
): Promise<T> {
  const res = await ctx.post(MOSAIC_GRAPHQL_URL, { data: { query, variables } });
  if (!res.ok()) throw new Error(`GraphQL HTTP ${res.status()}: ${await res.text()}`);
  const body = await res.json();
  if (body.errors) throw new Error(`GraphQL errors: ${JSON.stringify(body.errors)}`);
  return body.data as T;
}

// Count rows in a collection. Mosaic's list fields return page envelopes
// (`<plural>(limit!, offset!) -> <T>Page { items, total }`), so the real
// total comes straight off the envelope.
export async function countCollection(
  ctx: APIRequestContext,
  pluralField: string,
): Promise<number> {
  const data = await gql<Record<string, { total: number }>>(
    ctx,
    `query CertCount { ${pluralField}(limit: 1, offset: 0) { total } }`,
  );
  return data[pluralField]?.total ?? 0;
}
